### PR TITLE
added updated list of languages

### LINKED ISSUE #1557: Update donor support forms to reflect more language picklist options
In both Mozilla and Thunderbird donate support forms, update the HTML to support the expanded list of languages:

@stephaniemcv can you please paste the updated HTML into a comment in this issue.

### PR DESCRIPTION
**Pull request by danielfmiranda**
Closes #1557 
Related PRs/issues #

## Checklist

**Changes in Models:**
- [x] [Are my changes backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/master/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

### CODE REVIEW

**Comment by danielfmiranda** [comment]
Hi @TheoChevalier! 

I tagged you in this issue because I noticed that while all of the new options added are going to be translated, it appears that only the "None" and "Other"choices have a context set.

I was wondering if there was a reason for this, or if you would like me to add context for every choice. 
Thanks!

**Review by TheoChevalier — CHANGES_REQUESTED** [review]
Hey Daniel,

No need to add specific context to the language names, but it’s been done for "None" and "Other" for specific reasons, yes:
- Making sure these translations are only used here, as these strings exist in other (different) contexts
- Related to the above, help translators understand what they refer to, so they can adapt the translation (declension, genitive case, plural, etc). For instance in French, the word language  (langue) is feminine, so "None" must use the feminine form too, "Aucune".

I’ve filed #1561 as a follow up to properly sort this list in all languages as this becomes a problem with a longer list

**Comment by danielfmiranda** [comment]
Thanks for the catches @TheoChevalier! I have made the desired updates and re-requested review 😁

**Review by TheoChevalier — APPROVED** [review]
Thanks! Merging & getting translation started

**Pull request merged**
