### PR TITLE
Add custom middleware and URL resolvers for ISO 3166 language prefixes.

### LINKED ISSUE #167: Country code in URLs should be in uppercase
This is likely already planned, but filing it as I couldn’t find an issue tracking this.

For locales with a country code, the country code should be written in capital letters.

For instance:
https://donate-wagtail.mofostaging.net/en-us/ should be https://donate-wagtail.mofostaging.net/en-US/
https://donate-wagtail.mofostaging.net/pt-br/ should be https://donate-wagtail.mofostaging.net/pt-BR/

etc

### PR DESCRIPTION
**Pull request by solarissmoke**
Fixes #167.

This is probably going to need some thorough testing once we have some translations in place.

### CODE REVIEW

**Comment by TheoChevalier** [comment]
Note that it seems to break the language negotiation (https://donate-wagtail-staging-pr-187.herokuapp.com/ gives me a 404 instead of redirecting to https://donate-wagtail-staging-pr-187.herokuapp.com/fr)

**Comment by solarissmoke** [comment]
Thanks @TheoChevalier  - looks like I need to do a bit more work to get the language negotiation working - will sort this tomorrow.

**Comment by solarissmoke** [comment]
@TheoChevalier would you be able to test this deployment again? It should now address your comment above about 404 with your language preference.

**Comment by TheoChevalier** [comment]
Looks good with the latest, thanks @solarissmoke

**Pull request merged**
