### PR TITLE
updated footer to display full width button on mobile

### LINKED ISSUE #273: Fixing Footer UI on Donate
The footer on the donate site is looking good but there are still some tweaks to the UI that need to be made:

**Image for reference:**
Screen Shot 2019-09-27 at 11 31 45 AM

**List of requirements**
- [x] background colour for the footer should be #000000 instead of #111111
- [x] Increase margin/padding below 'Protect the internet ...' to 24px
- [x] Increase margin/padding below 'Join our email list ...' to 24px
- [x] Increase margin/padding below email signup form field to 16px
- [x] The sign up button should share the same row as the form field and occupy 3 columns with 16px spacing between itself and the form field
- [x] _All_ text, except for links, should be white #ffffff at full opacity
- [x] All links should be #269 B7B9FA (as well as hover states for Donate, Legal, License, Participation Guidelines and Privacy)
- Screen Shot 2019-09-27 at 11 32 32 AM
- [ ] The language picker is missing @alanmoo is that within scope of this project?

Screen Shot 2019-09-27 at 11 31 45 AM

For further reference, the footer on https://foundation.mozilla.org/en/ is exactly how the footer should be

### PR DESCRIPTION
**Pull request by danielfmiranda**
Closes #273

Link to sample page: [here](https://donate-wagta-273-footer-0aaaub.herokuapp.com/en-US/)

## Checklist

**Changes in Models:**
- [x] [Are my changes backward-compatible]

### CODE REVIEW

**Comment by danielfmiranda** [comment]
Hi @kristinashu!

Mavis and I have been working together on this ticket, and believe we have all the boxes checked.
 
We had to do some reformatting in the code in order to get the items in the desired order on mobile and were wondering if you can take a look at the staging site (link [here](https://donate-wagta-273-footer-0aaaub.herokuapp.com/en-US/) let us know if everything looks OK.

Thank you!

**Comment by kristinashu** [comment]
Thank you for working on this @danielfmiranda! 

Because the original ticket is old, I feel it might be a little out of date. Ideally the layout for the footer on the donate matches the layout of our main foundation site https://foundation.mozilla.org/. Some of the links my differ but the styling should ideally be the same. 

It might be out of the scope of the original ticket but would you mind taking a stab at aligning the styles as much as possible? Without getting into too much detail, I think some key factors are the width of the signup field (it is nice and wide on the foundation site), the overall ratio of the grid is a little different, and some the font sizes and colors are different.

**Comment by kristinashu** [comment]
footers

**Comment by danielfmiranda** [comment]
Hi @kristinashu sounds good! 

I believe we are going to merge this update in for now, and then open a new ticket/s for updating the footer to look exactly like the footer on the foundation site :)

**Review by KalobTaulien — APPROVED** [review]

**Pull request merged**
