### PR TITLE
Update check section and wire section on "Ways to Give" page

### LINKED ISSUE #1180: Add clarifying instructions to MoFo SEPA/BACS donation instructions
**Describe the bug**
MoFo is still receiving SEPA/BACS donations intended for MZLA/Thunderbird; this is a significant problem for accounting, as we are no longer acting as their "fiscal sponsor."  We need a clarifying note on the MoFo SEPA/BACS instructions to redirect Tbird supporters over to THEIR SEPA/BACS donation page.

**Expected behavior**
Clear instructions for MZLA/Thunderbird contributions, redirecting to their FAQ, posted on https://donate.mozilla.org/ways-to-give/#wire

**Additional context**

On https://donate.mozilla.org/en-US/ways-to-give/#wire, we need to add a sentence (indented in the middle below) 

We accept donations in Euros through Single European Payment Area (SEPA) transfer, and British Pounds through BACS transfer.

Note that for smaller (under 10 EUR or equivalent) donations, and especially for donations under 5 EUR or equivalent, we request that you donate via credit card or PayPal to help reduce Mozilla’s processing fees.

> Please also note that the Mozilla Foundation **cannot** accept SEPA or BACS transfers for MZLA/Thunderbird.  To contribute to MZLA/Thunderbird via SEPA or BACS transfer, please follow [these instructions](https://give.thunderbird.net/en-US/ways-to-give/#wire). 

Please remember that donations are deductible for U.S. income tax purposes only.

If your bank requests our physical address, it is 331 E. Evelyn Ave, Mountain View, CA 94041 USA.

### PR DESCRIPTION
**Pull request by mmmavis**
Related PRs/issues #1179

@WillatMozFdn please see review app pages below 😀 

- donate: https://donate-wagta-issue-1179-atnyap.herokuapp.com/en-US/ways-to-give/#check
- thunderbird: https://thunderbird-issue-1179--bgeo0r.herokuapp.com/en-US/ways-to-give/#check

---

Closes #1180 
- donate: https://donate-wagta-issue-1179-atnyap.herokuapp.com/en-US/ways-to-give/#wire

### CODE REVIEW

**Review by TheoChevalier — CHANGES_REQUESTED** [review]
Hey @mmmavis, I left a few notes related to localization, mind having a look and let me know if you have questions?

**Comment by mmmavis** [comment]
@TheoChevalier thanks for the feedback! Smart quotes and urls always got me as usually I'm just blindly copying and pasting provided text to code.

**Comment by WillatMozFdn** [comment]
This all looks good to me, Mavis @mmmavis -- cleared from my side to move to production.  THANKS!!!

**Review by TheoChevalier — APPROVED** [review]
Thanks Mavis, looking good!

**Pull request merged**
