### PR TITLE
Updated help and body text; localized. 

### LINKED ISSUE #1398: Update Thunderbird Help Text
Update help text in Thunderbird

https://github.com/mozilla/donate-wagtail/blob/1c3c0a24731fd0e5395b03852d92ab8cb67ac8b1/donate/templates/pages/core/contributor_support_page_master.html

- [x] @kristinashu approve final copy
- [ ] update copy (see below for copy)

### PR DESCRIPTION
**Pull request by KalobTaulien**
Closes #1398 

## Checklist
- [x] Update body text (see below)
- [x] Make "support page" text link to https://support.mozilla.org/products/thunderbird 
- [x] Localised the text

### CODE REVIEW

**Comment by kristinashu** [comment]
@KalobTaulien can you please let me know what URL the page is at for this PR? I thought it'd be here https://thunderbird-1398-update-ztqpys.herokuapp.com/en-US/help/ but I'm getting an Uh oh!

**Review by TheoChevalier — APPROVED** [review]
LGTM, thanks!

**Comment by KalobTaulien** [comment]
@kristinashu On my goodness, sorry I totally forgot about the review app link 🤦 

Try this link: https://thunderbird-1398-update-ztqpys.herokuapp.com/en-US/help/ I had to create the page in the Thunderbird review app because we don't have very much "Factory" code for Thunderbird.

**Review by kristinashu — APPROVED** [review]
Thank you for the link! English looks good!

**Pull request merged**
