### PR TITLE
WIP: Updated references of Mountain View location to San Francisco

### LINKED ISSUE #1359: Change all instances mentioning Mountain View to San Francisco
Our headquarters have moved to San Francisco, we need to replace all references to Mountain View to San Francisco, including addresses.
- [x] Search for any mention of the old headquarters in Mountain View and update them to our San Francisco office.
- [x] Verify if we need to submit any strings for localization.

### PR DESCRIPTION
**Pull request by danielfmiranda**
Closes #1359
Link to example page: [link](https://donate-wagta-1359-head--uelbdp.herokuapp.com/pt-PT/ways-to-give/)

## Checklist

**Changes in Models:**
- [x] [Are my changes backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/master/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

### CODE REVIEW

**Comment by danielfmiranda** [comment]
Hi Everyone, in ticket [#1359](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozilla/donate-wagtail/1359) one of the requirements is to check if we need to submit the new address for localization. 

After comparing the dev environment and prod, it appears that the localization is working the same:

Localization in Portuguese (PROD):

Screen Shot 2021-03-31 at 7 44 30 PM

Localization in Portuguese (Staging Env):

Screen Shot 2021-03-31 at 7 21 11 PM

**Comment by TheoChevalier** [comment]
Confirming no new strings are generated in this case since the address is stored in a variable. Things were set up this way primarily because we didn’t want translators to translate the address or change it by mistake, but also to support this use case, so it’s a nice payoff :)

**Comment by danielfmiranda** [comment]
Thanks for confirming Theo!

**Review by benhohner — APPROVED** [review]
R+

**Pull request merged**
